# openapi2-appengine.yaml
swagger: '2.0'
info:
  title: Polysnap API
  description: Sample API on API Gateway with an App Engine backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /stories:
    get:
      summary: manage stories
      operationId: stories
      x-google-backend:
        address: https://stories-dot-cloud-398911.lm.r.appspot.com/story
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /users:
    get:
      summary: manage users
      operationId: users
      x-google-backend:
        address: https://users-dot-cloud-398911.lm.r.appspot.com/users
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /messagereader:
    get:
      summary: manage reading messages
      operationId: messagereader
      x-google-backend:
        address: https://messagereader-dot-cloud-398911.lm.r.appspot.com/
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /messagesender:
    get:
      summary: manage sending messages
      operationId: messagesender
      x-google-backend:
        address: https://messagesender-dot-cloud-398911.lm.r.appspot.com/
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /messagestore:
    get:
      summary: manage storing messages
      operationId: messagestore
      x-google-backend:
        address: https://messagestore-dot-cloud-398911.lm.r.appspot.com/
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /media:
    get:
      summary: manage media
      operationId: media-service
      x-google-backend:
        address: https://media-service-dot-cloud-398911.lm.r.appspot.com/
      responses:
        '200':
          description: A successful response
          schema:
            type: string