version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: users-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - users-postgres-data:/var/lib/postgresql/data

  users-service:
    image: polysnap/users-service
    container_name: users-app
    environment:
      POSTGRESQL_ADDON_HOST: postgres
      POSTGRESQL_ADDON_PORT: 5432
      POSTGRESQL_ADDON_USER: ${DB_USERNAME}
      POSTGRESQL_ADDON_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_ADDON_DB: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  users-postgres-data:
