version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: stories-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - stories-postgres-data:/var/lib/postgresql/data

  stories-service:
    image: polysnap/stories-service
    container_name: stories-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  stories-postgres-data:
