name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Change to messaging-service directory
      run: cd ./messaging-service
    - name: LS
      run: ls

    - name: Install dependencies
      run: npm install # Change to your package manager (e.g., yarn)

    - name: Build
      run: npm run build # Change to your build command

    - name: 'Google auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'principal://iam.googleapis.com/projects/241792550769/locations/global/workloadIdentityPools/polysnap/subject/SUBJECT_ATTRIBUTE_VALUE'
        service_account: "cloud-398911@appspot.gserviceaccount.com"

   

    - name: Deploy to App Engine (from messaging-service)
      run: gcloud app deploy --quiet
